LEG-525: Upgrade Sinai ARK minting script to Python 3
UCLALibrary/SLDP_ARK_mint pull request #5
Opened 2022-09-07 18:34 UTC by ztucker4

Relates to [LEG-525](https://jira.library.ucla.edu/browse/LEG-525), which called for three changes to the Sinai ARK minting script, `sinai_work_page_ark.py`:
1. Update script to use Python 3
2. Change the use of "Altidentifier.local" in matching page and work records to use "Shelfmark" instead
3. Allow use of filenames like "works*.csv" for the Works file

To test, follow Installation and Usage instructions in latest version of README. Test files can be found attached to the Jira ticket as a .zip file. You will also need the EZID username (ucla-library) and password, and an ARK shoulder (I used ark:/99999/fk4 in my testing). The script takes a few minutes to run with this size test data. ARKs will be written directly into existing Parent ARK and Item ARK columns of the .csv files.

2022-09-08 00:04 UTC, akohler requested changes
@ztucker4 - This looks quite good; just a few changes which should be made (or considered, in 1-2 cases).

The tests pass for me.  I got no errors running it, and the sample CSV files were updated as expected (as far as I know).  All of the CSV files contained ARKs with the given shoulder.

Please make (or consider :) ) the suggested changes.  We'll see what Dawn says when she tests, in case there are related changes.

Thanks --Andy

2022-09-08 00:04 UTC, akohler commented on README.md
> +	$ git clone https://github.com/UCLALibrary/SLDP_ARK_mint
There's a missing or incomplete step here.  `git clone https://github.com/UCLALibrary/SLDP_ARK_mint` creates a new `SLDP_ARK_mint` directory inside of `manuscript_arks`.  The subsequent steps (the venv & installs)  should take place in `SLDP_ARK_mint`.

So either insert a `cd SLDP_ARK_mint`, or change the clone to `git clone https://github.com/UCLALibrary/SLDP_ARK_mint .` (adding a space and period to the end), so the repo gets cloned directly into the current `manuscript_arks` instead of a new sub-directory.

2022-09-08 00:04 UTC, akohler commented on sinai_work_page_ark.py
> +    return response.stdout.split()[4][2:-1].decode()
Please add a comment documenting what's being parsed from the response.  From the method name we know it's a `session_id`, but a comment showing it in the context of `response.stdout` will help document what's expected.

2022-09-08 00:04 UTC, akohler commented on sinai_work_page_ark.py
> +        sys.exit(1)
This needs an `import sys`.

2022-09-08 00:04 UTC, akohler commented on sinai_work_page_ark.py
> +    session = get_session_id()
This confuses me, since I don't see a session being created from a session id.  I think these should match - either `session_id = get_session_id()` or `session = get_session()`, whichever best matches the intent of this value.

2022-09-08 00:04 UTC, akohler commented on sinai_work_page_ark.py
> +    except Exception as e:
Generic exception handling is convenient, but discouraged.  It's better to be specific: what can go wrong in the `try` block?  That said, it's the end of the program, there's a `finally` to tidy things up... but part of exception handling is documenting what you know can go wrong.  If a lot of different exceptions could occur here, it's OK with me to add a comment acknowledging them and stating that they don't need to be handled.

2022-09-08 00:04 UTC, akohler commented on test/test.py
> +        ns = list(range(10))
Why the `list()` conversion?  A `range` has the same iteration as a `list`:
```
>>> ns = range(10)
>>> nl = list(range(10))
>>> for n in ns: print(n)
...
0
1
2
3
4
5
6
7
8
9
>>> for n in nl: print(n)
...
0
1
2
3
4
5
6
7
8
9
```
The tests pass whether the `list()` is there or not, so I recommend removing those 2 additions (lines 28 and 31), or add a comment documenting why the change.

2022-09-08 21:38 UTC, akohler approved these changes
@ztucker4 Thanks for making the changes.  Since Dawn plans to test tomorrow, I'll hold off on merging this PR until end of tomorrow.

2022-09-09 15:21 UTC, kirschbombe commented
Everything works great :) There is one small change that would be helpful -- could we strip the trailing white space from the file directly path input? If someone drags the directory into the terminal to write the path, Terminal adds a space at the end which prevents the terminal from recognizing the path.

Thanks!

2022-09-09 16:07 UTC, kirschbombe approved these changes

2022-09-09 16:18 UTC, akohler commented
Thanks all - merging.

2022-09-09 16:19 UTC, merged